const hotDrink = require('../controllers/hotDrink.controller')
const brewMenu = require('../controllers/brewMenu.controller')
const hotCoffee = require('../controllers/hotCoffee.controller')
const Cart = require('../controllers/cart.controller')
const ColdCoffee = require('../controllers/coldCoffee.controller')
const BlendedDrink = require('../controllers/blendedDrink.controller')
const Pastry = require('../controllers/pastry.controller')
const EggBite = require('../controllers/eggBite.controller')
const Bagel= require('../controllers/bagel.controller')
const BreakfastSandwich = require('../controllers/breakfastSandwich.controller')
const BreakfastBurrito = require('../controllers/breakfastBurrito.controller')
const berryMenu =require('../controllers/berryMenu.controller')
const FreshJuice = require('../controllers/freshJuice.controller')
const Smoothie = require('../controllers/smoothie.controller')
const FreshFruitBowl = require('../controllers/freshFruitBowls.controller')
const Sandwich = require('../controllers/sandwich.controller')

module.exports = (app) => {
    app.get('/api/HotDrinks', hotDrink.getItems)
    app.get('/api/HotDrinks/:id', hotDrink.getOneItem)
    app.post('/api/hotdrink', hotDrink.createItem)
    app.put('/api/hotdrink/:id', hotDrink.updateItem)
    app.delete('/api/hotdrink/:id', hotDrink.deleteItem)

    app.get('/api/HotCoffees', hotCoffee.getItems)
    app.get('/api/HotCoffees/:id', hotCoffee.getOneItem)
    app.post('/api/hotCoffee', hotCoffee.createItem)
    app.put('/api/hotCoffee/:id', hotCoffee.updateItem)
    app.delete('/api/hotCoffee/:id', hotCoffee.deleteItem)

    app.get('/api/ColdCoffees', ColdCoffee.getItems)
    app.get('/api/ColdCoffees/:id', ColdCoffee.getOneItem)
    app.post('/api/ColdCoffee', ColdCoffee.createItem)
    app.put('/api/ColdCoffee/:id', ColdCoffee.updateItem)
    app.delete('/api/ColdCoffee/:id', ColdCoffee.deleteItem)

    app.get('/api/BlendedDrinks', BlendedDrink.getItems)
    app.get('/api/BlendedDrinks/:id', BlendedDrink.getOneItem)
    app.post('/api/BlendedDrink', BlendedDrink.createItem)
    app.put('/api/BlendedDrink/:id', BlendedDrink.updateItem)
    app.delete('/api/BlendedDrink/:id', BlendedDrink.deleteItem)

    app.get('/api/Pastries', Pastry.getItems)
    app.get('/api/Pastries/:id', Pastry.getOneItem)
    app.post('/api/Pastry', Pastry.createItem)
    app.put('/api/Pastry/:id', Pastry.updateItem)
    app.delete('/api/Pastry/:id', Pastry.deleteItem)

    app.get('/api/EggBites', EggBite.getItems)
    app.get('/api/EggBites/:id', EggBite.getOneItem)
    app.post('/api/EggBite', EggBite.createItem)
    app.put('/api/EggBite/:id', EggBite.updateItem)
    app.delete('/api/EggBite/:id', EggBite.deleteItem)

    app.get('/api/Bagels', Bagel.getItems)
    app.get('/api/Bagels/:id', Bagel.getOneItem)
    app.post('/api/Bagel', Bagel.createItem)
    app.put('/api/Bagel/:id', Bagel.updateItem)
    app.delete('/api/Bagel/:id', Bagel.deleteItem)

    app.get('/api/BreakfastSandwiches', BreakfastSandwich.getItems)
    app.get('/api/BreakfastSandwiches/:id', BreakfastSandwich.getOneItem)
    app.post('/api/BreakfastSandwich', BreakfastSandwich.createItem)
    app.put('/api/BreakfastSandwich/:id', BreakfastSandwich.updateItem)
    app.delete('/api/BreakfastSandwich/:id', BreakfastSandwich.deleteItem)

    app.get('/api/BreakfastBurritos', BreakfastBurrito.getItems)
    app.get('/api/BreakfastBurritos/:id', BreakfastBurrito.getOneItem)
    app.post('/api/BreakfastBurrito', BreakfastBurrito.createItem)
    app.put('/api/BreakfastBurrito/:id', BreakfastBurrito.updateItem)
    app.delete('/api/BreakfastBurrito/:id', BreakfastBurrito.deleteItem)

    app.get('/api/brewMenu', brewMenu.getItems)
    app.get('/api/brewMenu/:id', brewMenu.getOneItem)
    app.post('/api/brewMenu', brewMenu.createItem)
    app.put('/api/brewMenu/:id', brewMenu.updateItem)
    app.delete('/api/brewMenu/:id', brewMenu.deleteItem)
    
    app.get('/api/berryMenu', berryMenu.getItems)
    app.get('/api/berryMenu/:id', berryMenu.getOneItem)
    app.post('/api/berryMenu', berryMenu.createItem)
    app.put('/api/berryMenu/:id', berryMenu.updateItem)
    app.delete('/api/berryMenu/:id', berryMenu.deleteItem)

    app.get('/api/FreshJuices', FreshJuice.getItems)
    app.get('/api/FreshJuices/:id', FreshJuice.getOneItem)
    app.post('/api/FreshJuice', FreshJuice.createItem)
    app.put('/api/FreshJuice/:id', FreshJuice.updateItem)
    app.delete('/api/FreshJuice/:id', FreshJuice.deleteItem)

    app.get('/api/Smoothies', Smoothie.getItems)
    app.get('/api/Smoothies/:id', Smoothie.getOneItem)
    app.post('/api/Smoothie', Smoothie.createItem)
    app.put('/api/Smoothie/:id', Smoothie.updateItem)
    app.delete('/api/Smoothie/:id', Smoothie.deleteItem)

    app.get('/api/FreshFruitBowls', FreshFruitBowl.getItems)
    app.get('/api/FreshFruitBowls/:id', FreshFruitBowl.getOneItem)
    app.post('/api/FreshFruitBowl', FreshFruitBowl.createItem)
    app.put('/api/FreshFruitBowl/:id', FreshFruitBowl.updateItem)
    app.delete('/api/FreshFruitBowl/:id', FreshFruitBowl.deleteItem)

    app.get('/api/Sandwiches', Sandwich.getItems)
    app.get('/api/Sandwiches/:id', Sandwich.getOneItem)
    app.post('/api/Sandwich', Sandwich.createItem)
    app.put('/api/Sandwich/:id', Sandwich.updateItem)
    app.delete('/api/Sandwich/:id', Sandwich.deleteItem)


    app.get('/api/Cart', Cart.getItems)
    app.get('/api/Cart/:id', Cart.getOneItem)
    app.post('/api/Cart', Cart.createItem)
    app.put('/api/Cart/:id', Cart.updateItem)
    app.delete('/api/Cart/:id', Cart.deleteItem)
}

